source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

target 'NetworkingServiceKit_Example' do
  pod 'NetworkingServiceKit', :path => '../'
  pod 'NetworkingServiceKit/ReactiveSwift', :path => '../'
  
  target 'NetworkingServiceKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '3.1.1'
    pod 'Nimble'
    pod 'Mockingjay', :git => 'https://github.com/kylef/Mockingjay.git', :tag => '3.0.0-alpha.1'
  end
end
