source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:makingspace/iOS-Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'NetworkingServiceKit_Example' do
  pod 'NetworkingServiceKit', :path => '../'
  pod 'NetworkingServiceKit/ReactiveSwift', :path => '../'
  
  target 'NetworkingServiceKit_Tests' do
    inherit! :search_paths

    pod 'Quick',:git => 'git@github.com:Quick/Quick.git', :branch => 'master'
    pod 'Nimble',:git => 'git@github.com:Quick/Nimble.git', :branch => 'master'
    pod 'URITemplate', :git => 'git@github.com:darkzlave/URITemplate.swift.git', :branch => 'master'
    pod 'Mockingjay', :git => 'git@github.com:darkzlave/Mockingjay.git', :branch => 'master'
  end
end
