source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:makingspace/iOS-Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'NetworkingServiceKit_Example' do
  pod 'NetworkingServiceKit', :path => '../'
  pod 'NetworkingServiceKit/ReactiveSwift', :path => '../'
  
  target 'NetworkingServiceKit_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'Mockingjay'
  end
end
